approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@primevue/icons@*":
    peerDependencies:
      vue: ^3.5.0
  primevue@*:
    peerDependencies:
      vue: ^3.5.0
